# MkDocs configuration for builds with material theme

site_name: Percona Documentation Style Guide
site_description: Style Guide
site_author: Percona LLC
copyright: Percona LLC, &#169; 2022

repo_name: percona/doc-style-guide
repo_url: https://github.com/percona/doc-style-guide
edit_uri: edit/main/docs/

use_directory_urls: false

# Theme setup
theme:
  name: material
  logo: _images/percona-logo.svg
  favicon: _images/percona-favicon.ico
  custom_dir: _resource/overrides/
  font:
    text: Poppins
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: percona-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

features:
  - search.highlight
  - search.share
  - navigation.top
  - navigation.tracking
  - content.action.copy
  - content.action.view
  - content.account.edit


extra_css:
  - https://unicons.iconscout.com/release/v3.0.3/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css
  - css/percona.css

extra_javascript:
  - js/version-select.js

markdown_extensions:
  abbr: {}
  attr_list: {}
  toc:
    permalink: True
    title: On this page
    toc_depth: 5
  admonition: {}
  footnotes: {}
  def_list: {} # https://michelf.ca/projects/php-markdown/extra/#def-list
  meta: {}
  md_in_html: {}
  smarty:
      {smart_angled_quotes: true}
  pymdownx.details: {}
  pymdownx.mark: {}
  pymdownx.smartsymbols: {}
  pymdownx.tabbed: 
      {alternate_style: true}
  pymdownx.tilde: {}
  pymdownx.superfences: {}
  pymdownx.highlight:
      linenums: false
  pymdownx.inlinehilite: {}
  pymdownx.snippets: {}
  pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

       

plugins:
  section-index: {}
  search: 
    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  git-revision-date-localized: 
    enable_creation_date: true
    enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
  macros:
      include_yaml:
#        - 'variables.yml' # Use in markdown as '{{ VAR }}'
# exclude: # Don't process these files
#      glob:
#         - file.md
  
  mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null


nav:
  - "Home": "overview.md"
  - Storytelling:
    - translation.md
    - voice-and-tone.md
    - structure.md
    - cross-reference.md
  - Text:
    - text.md
    - hyphens.md
    - paragraphs.md
    - lists.md
    - headings.md
    - tables.md
    - graphics.md
    - callouts.md
    - code.md
    - sql-guidelines.md
    - links.md
    - legal.md
    - reference.md
  - Grammar:
    - grammar.md
    - capitalization.md
    - punctuation.md
    - spelling.md
    - word-use.md
    - numbers.md
  - Writing:
    - file-naming-SEO.md
    - rules-for-docs.md
  - Guidelines:
    - structure-release-notes.md
  - Markup:
    - markup.md
  - Copyright and licensing:
      - copyright.md
  - Trademark policy:
      - trademark-policy.md 

